### ISSUE TITLE
Cannot read property "map" of undefined

### ISSUE THREAD

**Issue by derekschinke** [pelmers/GPXSpliceApp#2]
For some GPX tracks, I'm unable to import, and the app returns the error `Cannot read property "map" of undefined`. Unsure of what exactly is causing this for some tracks and not others.

**Comment by pelmers** [comment]
Can you share an example file?

**Comment by derekschinke** [comment]
I can't post the `.gpx` files directly because Github doesn't support the file type, but here's a `.zip` with the `.gpx` files I was attempting to combine.

I was able to combine them successfully using a different program, [gpx.studio](https://gpx.studio/)

[example-gpx.zip](https://github.com/user-attachments/files/15597067/example-gpx.zip)

**Comment by pelmers** [comment]
thanks! I'll take a look and see what went wrong, most likely this weekend

**Comment by pelmers** [comment]
should be fixed in version 1.0.7, it will release once it's gone through the app reviews
